FILE_CONSTRAINTS_ERROR_MESSAGE = "Error at line {i}: The line must be empty, a"
" comment (a line which starts with a '#') or a hub/connection. You can find t"
"he constraints of them below:\n\nHub.\nhub: <name> <x_coordinate> <y_coordina"
"te> [zone=<normal|blocked|restricted|priority> color=<string> max_drones=<pos"
"itive_number>]\nFor starter and end hubs there is only one difference between"
", they start with either start_hub or end_hub correspondingly.\n\nConnection."
"\nconnection: <hub1>-<hub2> [max_link_capacity=<positive_number>]\nThe hubs m"
"ust be created previously.\n\nTake in mind that the data between the clasps a"
"re optional, but must follow the same syntaxis. If any is choosen."
