[tool.poetry]
name = "ex1"
version = "1.0.0"
description = "Hello, world!"
authors = ["ErjieIsHeree <erjieisheree@gmail.com>"]

[tool.poetry.dependencies]
pandas = "~3.0.1"
numpy = "~2.4.4"
requests = "~2.31"
matplotlib = "~3.10.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"